# Usa a imagem oficial do PHP com Apache
FROM php:8.2-apache

# Instala a extensão do PDO para MySQL
RUN docker-php-ext-install pdo pdo_mysql

# Copia todos os arquivos do projeto para dentro do container
COPY . /var/www/html/

# Permissões corretas
RUN chown -R www-data:www-data /var/www/html
